kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: khaos-webhook-crb 
  labels:
    app: khaos-webhook
subjects:
- kind: ServiceAccount
  name: khaos-webhook-sa
  namespace: khaos-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: khaos-webhook-cr