apiVersion: apps/v1
kind: Deployment
metadata:
  name: khaos-webhook-deployment
  namespace: khaos-webhook
  labels:
    app: khaos-webhook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: khaos-webhook
  template:
    metadata:
      labels:
        app: khaos-webhook
    spec:
      containers:
        - name: khaos-webhook
          env:
          - name: TRACE_ONLY
            valueFrom:
              configMapKeyRef:
                name: khaos-config
                key: traceonly
          image: cloudoperators/khaos:0.1.0
          imagePullPolicy: Always
          args:
            - -tlsCertFile=/etc/webhook/certs/cert.pem
            - -tlsKeyFile=/etc/webhook/certs/key.pem
            - -alsologtostderr
            - -v=4
            - 2>&1
          volumeMounts:
            - name: webhook-certs
              mountPath: /etc/webhook/certs
              readOnly: true
          
      volumes:
        - name: webhook-certs
          secret:
            secretName: khaos-webhook-certs
