apiVersion: v1
kind: Service
metadata:
  name: khaos-webhook-svc
  namespace: khaos-webhook
  labels:
    app: khaos-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: khaos-webhook
