apiVersion: v1
kind: Service
metadata:
  name: ktest-webhook-svc
  namespace: ktest-webhook
  labels:
    app: ktest-webhook
spec:
  ports:
  - port: 443
    targetPort: 443
  selector:
    app: ktest-webhook
